### PR TITLE
Add nloptr

### PR DESCRIPTION
**Pull request by pfistfl**
As I want to use it for threshold tuning I added nloptr. 
It basically allows for nonlinear optmization + equality / inequality constraints.
Currently we can only use parts of nloptr as we usually have no gradient information available, I guess in order to extend to this, we should decide how this would look like. 

Currently the `"TunerNloptr with int params and trafo"` unit tests fail, but this does not seem to be on my side.

### CODE REVIEW

**Comment by mllg** [comment]
Out of curiosity: is nloptr really so much better suited for threshold tuning than `optim()`?

**Comment by pfistfl** [comment]
I do not know how this is for threshold tuning, empirically it at least seems to hold for [ensemble weights](https://escholarship.org/content/qt3kb142r2/qt3kb142r2.pdf) (page 47).

**Comment by pfistfl** [comment]
What is the status here? I think you wanted to look at this @be-marc @jakob-r  or is any action from my side required?

**Comment by jakob-r** [comment]
I guess either @be-marc or I have to adapt that to all the changes after #248 is merged.

**Comment by be-marc** [comment]
@pfistfl Sorry I missed that you already create a PR. I used the code you posted [here](https://github.com/mlr-org/mlr3pipelines/blob/91273aa34e53564db5e0b0c3aafda1149600fb83/R/Optimizer.R) for the implementation. The only difference is that I sticked more to the package defaults. So `x0` is not create with a random design and `algorithm` is also a required parameter. You can find the code in `bbotk::OptimizerNLoptr` and `mlr3tuning::TunerNLoptr`. If you want to improve something, open a new issue or PR.

**Pull request closed without merging**
